### ISSUE TITLE
MYSQL Error: Connection to localhost failed

### ISSUE THREAD

**Issue by markolofsen** [niiknow/vestacp#57]
When I trying create new MySql DB I getting error `Error: Connection to localhost failed`
Also in ....:8083/list/db/  I see only **phppgadmin** link, but direct link to phpmyadmin `http://...../phpmyadmin/` available.

**My sh my-startup.sh** 
```
#!/bin/sh

# re-enable phpmyadmin and phppgadmin
rsync -a /etc/apache2/conf-d/php*.conf /etc/apache2/conf.d

# required startup and of course vesta
cd /etc/init.d/
./disable-transparent-hugepages defaults

# the 5 services below are enabled to support mininum default backup job
./apache2 start
./mysql start

# delete defult postgres admindb if not use, then comment out the line below
# ./postgresql start
./nginx start
./vesta start

# && ./exim4 start \
# && ./dovecot start \
# && ./clamav-daemon start \
# && ./spamassassin start \
# && ./php7.1-fpm start \
# && ./fail2ban start \ # -- only if you run with: --cap-add=NET_ADMIN --cap-add=NET_RAW

```

**Comment by gamma05772** [comment]
pls get the last version 1.3.7 ,the issue is fixed

**Comment by markolofsen** [comment]
@gamma05772 
Strange, but http://......ip/phpmyadmin/ still doesn't work

**Comment by noogen** [comment]
@markolofsen it is disabled by default, for security.  You can ssh in and re-enable it with:

```
rsync -a /etc/apache2/conf-d/phpmy*.conf /etc/apache2/conf.d
```
